### ISSUE TITLE
ToInt might throw an exception

### ISSUE THREAD

**Issue by aligoren** [ardalis/Ardalis.Extensions#8]
https://github.com/ardalis/Ardalis.Extensions/blob/26e3786b31659f9f5c29b5d0011a4361b2cc368f/src/Ardalis.Extensions/StringExtensions.cs#L36-L44

According to the above code block, we can convert a string to an integer.

I think this may fail in some cases.

For example, I get a result from an HTTP request.  Let's assume it contains a value like this;

```cs
int a = response.Age.ToInt(); // response.Age returns 3A
```

In this case, you'll get an exception because of the value 3A.

What if we change the code block like this;

```cs
public static int ToInt(this string input)
{
	int number = 0;

	if (string.IsNullOrEmpty(input))
	{
		return number;
	}

	int.TryParse(input, out number);

	return number;
}
```

Otherwise, you could get an exception like that;

```cs
Run-time exception (line 14): Input string was not in a correct format.

Stack Trace:

[System.FormatException: Input string was not in a correct format.]
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at StringExtensions.ToInt(String input) :line 14
   at Program.Main() :line 24
```

**Comment by aligoren** [comment]
Sorry. This was fixed in #7
